experiment_folder: experiments/bcb_train/

experiment_name: bcb_train

results_folder: results/

defaults:
  data_split: train
  dataset: bigcodebench

runs:
  attacks:
    eval_mode: attack
    system_prompt: self_rec_attack_policy_prompt_bcb
    save_path: generator/attacks.eval
    model: tinker/Qwen/Qwen3-30B-A3B-Instruct-2507

  honeypots:
    eval_mode: attack
    system_prompt: self_rec_attack_policy_prompt_bcb
    save_path: generator/honeypots.eval
    model: tinker/meta-llama/Llama-3.2-3B
