experiment_folder: experiments/apps/control_self_rec

results_folder: results/no_backdoors/none_sft_honest/

experiment_name: Self Rec SFT Honest (No Backdoors)

defaults:
  monitors:
    - untrusted_collusion_monitor:
        model_info:
          model: openai/ft:gpt-4.1-2025-04-14:lasr-labs:gemini-2-5-flash-honest:CQmnG0bI
          system_prompt: SELF_REC_UNTRUSTED_MONITOR_COLLUSION_SYSTEM_PROMPT
          base_prompt: MONITOR_USER_PROMPT
        remove_comments: true
        transformed: false

    - trusted_backdoor_monitor:
        model_info:
          model: openai/gpt-4o-mini
          system_prompt: DEFAULT_HONEST_MONITOR_SYSTEM_PROMPT
          base_prompt: MONITOR_USER_PROMPT
        remove_comments: true
        transformed: false

    - untrusted_backdoor_monitor:
        model_info:
          model: openai/gpt-4.1-2025-04-14
          system_prompt: DEFAULT_HONEST_MONITOR_SYSTEM_PROMPT
          base_prompt: MONITOR_USER_PROMPT
        remove_comments: true
        transformed: false
runs:
  attacks:
    eval_path: generator/no_backdoors/honest.eval
    save_path: outputs/no_backdoors/none_sft_honest/attack_monitor_results.eval
    monitors:
      - untrusted_collusion_monitor
      - trusted_backdoor_monitor
      - untrusted_backdoor_monitor

  honest:
    eval_path: generator/no_backdoors/honest.eval
    save_path: outputs/no_backdoors/none_sft_honest/honest_monitor_results.eval
    monitors:
      - untrusted_collusion_monitor
      - trusted_backdoor_monitor
      - untrusted_backdoor_monitor

  honeypots:
    eval_path: generator/no_backdoors/honeypots.eval
    save_path: outputs/no_backdoors/none_sft_honest/honeypots_monitor_results.eval
    monitors:
      - untrusted_collusion_monitor
      - trusted_backdoor_monitor
      - untrusted_backdoor_monitor
