experiment_folder: experiments/apps/causal

results_folder: results/causal_none_train_causal_none_eval/

experiment_name: causal none train | causal none eval

defaults:
  monitors:
    - untrusted_collusion_monitor:
        model_info:
          model: openai/ft:gpt-4.1-2025-04-14:lasr-labs:causal-base:CSQTsO5j:ckpt-step-2100
          system_prompt: SELF_REC_UNTRUSTED_MONITOR_COLLUSION_SYSTEM_PROMPT
          base_prompt: MONITOR_USER_PROMPT
        remove_comments: true
        transformed: false

    - trusted_backdoor_monitor:
        model_info:
          model: openai/gpt-4o-mini
          system_prompt: DEFAULT_HONEST_MONITOR_SYSTEM_PROMPT
          base_prompt: MONITOR_USER_PROMPT
        remove_comments: true
        transformed: false

    - untrusted_backdoor_monitor:
        model_info:
          model: openai/gpt-4.1-2025-04-14
          system_prompt: DEFAULT_HONEST_MONITOR_SYSTEM_PROMPT
          base_prompt: MONITOR_USER_PROMPT
        remove_comments: true
        transformed: false
runs:
  attacks:
    eval_path: generator/attacks.eval
    save_path: outputs/causal_none_train_causal_none_eval/attack_monitor_results.eval
    monitors:
      - untrusted_collusion_monitor
      - trusted_backdoor_monitor
      - untrusted_backdoor_monitor

  honest:
    eval_path: generator/honest.eval
    save_path: outputs/causal_none_train_causal_none_eval/honest_monitor_results.eval
    monitors:
      - untrusted_collusion_monitor
      - trusted_backdoor_monitor
      - untrusted_backdoor_monitor

  honeypots:
    eval_path: generator/honeypots.eval
    save_path: outputs/causal_none_train_causal_none_eval/honeypots_monitor_results.eval
    monitors:
      - untrusted_collusion_monitor
      - trusted_backdoor_monitor
      - untrusted_backdoor_monitor
