experiment_folder: experiments/apps/causal

results_folder: results/causal_paraphrased_train_causal_paraphrased_eval/

experiment_name: causal paraphrased train | causal paraphrased eval

defaults:
  monitors:
    - untrusted_collusion_monitor:
        model_info:
          model: openai/ft:gpt-4.1-2025-04-14:lasr-labs:causal-paraphrased:CS8Pm0LQ:ckpt-step-2100
          system_prompt: SELF_REC_UNTRUSTED_MONITOR_COLLUSION_SYSTEM_PROMPT
          base_prompt: MONITOR_USER_PROMPT
        remove_comments: false
        transformed: true

    - trusted_backdoor_monitor:
        model_info:
          model: openai/gpt-4o-mini
          system_prompt: DEFAULT_HONEST_MONITOR_SYSTEM_PROMPT
          base_prompt: MONITOR_USER_PROMPT
        remove_comments: true
        transformed: false

    - untrusted_backdoor_monitor:
        model_info:
          model: openai/gpt-4.1-2025-04-14
          system_prompt: PARAPHRASED_HONEST_MONITOR_SYSTEM_PROMPT
          base_prompt: MONITOR_USER_PROMPT
        remove_comments: false
        transformed: true
runs:
  attacks:
    eval_path: transforms/paraphrased/attack_transformed.eval
    save_path: outputs/causal_paraphrased_train_causal_paraphrased_eval/attack_monitor_results.eval
    monitors:
      - untrusted_collusion_monitor
      - trusted_backdoor_monitor
      - untrusted_backdoor_monitor

  honest:
    eval_path: transforms/paraphrased/honest_transformed.eval
    save_path: outputs/causal_paraphrased_train_causal_paraphrased_eval/honest_monitor_results.eval
    monitors:
      - untrusted_collusion_monitor
      - trusted_backdoor_monitor
      - untrusted_backdoor_monitor

  honeypots:
    eval_path: transforms/paraphrased/honeypots_transformed.eval
    save_path: outputs/causal_paraphrased_train_causal_paraphrased_eval/honeypots_monitor_results.eval
    monitors:
      - untrusted_collusion_monitor
      - trusted_backdoor_monitor
      - untrusted_backdoor_monitor
