experiment_folder: experiments/bigcodebench_open/acausal

results_folder: results/paraphrased_base/

experiment_name: Acausal Summarised

defaults:
  monitors:
    - untrusted_collusion_monitor:
        model_info:
          model: tinker/Qwen/Qwen3-30B-A3B-Instruct-2507
          system_prompt: ACAUSAL_UNTRUSTED_MONITOR_COLLUSION_SYSTEM_PROMPT
          base_prompt: MONITOR_USER_PROMPT
        remove_comments: false
        transformed: true

    - trusted_backdoor_monitor:
        model_info:
          model: tinker/Qwen/Qwen3.5-4B
          system_prompt: DEFAULT_HONEST_MONITOR_SYSTEM_PROMPT
          base_prompt: MONITOR_USER_PROMPT
        remove_comments: true
        transformed: false

    - untrusted_backdoor_monitor:
        model_info:
          model: tinker/Qwen/Qwen3-30B-A3B-Instruct-2507
          system_prompt: PARAPHRASED_HONEST_MONITOR_SYSTEM_PROMPT
          base_prompt: MONITOR_USER_PROMPT
        remove_comments: false
        transformed: true
runs:
  attacks:
    eval_path: transforms/paraphrased/attack_transformed.eval
    save_path: outputs/paraphrased_base/attack_monitor_results.eval
    monitors:
      - untrusted_collusion_monitor
      - trusted_backdoor_monitor
      - untrusted_backdoor_monitor

  honest:
    eval_path: transforms/paraphrased/honest_transformed.eval
    save_path: outputs/paraphrased_base/honest_monitor_results.eval
    monitors:
      - untrusted_collusion_monitor
      - trusted_backdoor_monitor
      - untrusted_backdoor_monitor

  honeypots:
    eval_path: transforms/paraphrased/honeypots_transformed.eval
    save_path: outputs/paraphrased_base/honeypots_monitor_results.eval
    monitors:
      - untrusted_collusion_monitor
      - trusted_backdoor_monitor
      - untrusted_backdoor_monitor
