experiment_folder: experiments/bigcodebench_open/causal

experiment_name: causal

results_folder: results/

defaults:
  data_split: test
  dataset_type: bigcodebench

runs:
  attacks:
    eval_mode: attack
    system_prompt: causal_attack_policy_prompt_bcb
    save_path: generator/attacks.eval
    model: tinker/Qwen/Qwen3-30B-A3B-Instruct-2507
