experiment_folder: experiments/apps/self_rec

results_folder: results/none_base/tm_only

experiment_name: Baseline without Untrusted Monitoring

defaults:
  disable_untrusted_monitor: true
  monitors:
    - untrusted_collusion_monitor:
        model_info:
          model: openai/gpt-4.1-2025-04-14
          system_prompt: SELF_REC_UNTRUSTED_MONITOR_COLLUSION_SYSTEM_PROMPT
          base_prompt: MONITOR_USER_PROMPT
        remove_comments: true
        transformed: false

    - trusted_backdoor_monitor:
        model_info:
          model: openai/gpt-4o-mini
          system_prompt: DEFAULT_HONEST_MONITOR_SYSTEM_PROMPT
          base_prompt: MONITOR_USER_PROMPT
        remove_comments: true
        transformed: false

    - untrusted_backdoor_monitor:
        model_info:
          model: openai/gpt-4.1-2025-04-14
          system_prompt: DEFAULT_HONEST_MONITOR_SYSTEM_PROMPT
          base_prompt: MONITOR_USER_PROMPT
        remove_comments: true
        transformed: false
runs:
  attacks:
    eval_path: generator/attacks.eval
    save_path: outputs/none_base/attack_monitor_results.eval
    monitors:
      - untrusted_collusion_monitor
      - trusted_backdoor_monitor
      - untrusted_backdoor_monitor

  honest:
    eval_path: generator/honest.eval
    save_path: outputs/none_base/honest_monitor_results.eval
    monitors:
      - untrusted_collusion_monitor
      - trusted_backdoor_monitor
      - untrusted_backdoor_monitor

  honeypots:
    eval_path: generator/honeypots.eval
    save_path: outputs/none_base/honeypots_monitor_results.eval
    monitors:
      - untrusted_collusion_monitor
      - trusted_backdoor_monitor
      - untrusted_backdoor_monitor
