experiment_folder: experiments/apps_open/acausal

results_folder: results/minified_base/

experiment_name: Acausal Minified

defaults:
  monitors:
    - untrusted_collusion_monitor:
        model_info:
          model: tinker/Qwen/Qwen3-30B-A3B-Instruct-2507
          system_prompt: ACAUSAL_UNTRUSTED_MONITOR_COLLUSION_SYSTEM_PROMPT
          base_prompt: MONITOR_USER_PROMPT
        remove_comments: false
        transformed: true

    - trusted_backdoor_monitor:
        model_info:
          model: tinker/Qwen/Qwen3-8B
          system_prompt: DEFAULT_HONEST_MONITOR_SYSTEM_PROMPT
          base_prompt: MONITOR_USER_PROMPT
        remove_comments: true
        transformed: false

    - untrusted_backdoor_monitor:
        model_info:
          model: tinker/Qwen/Qwen3-30B-A3B-Instruct-2507
          system_prompt: MINIFIED_HONEST_MONITOR_SYSTEM_PROMPT
          base_prompt: MONITOR_USER_PROMPT
        remove_comments: false
        transformed: true
runs:
  attacks:
    eval_path: transforms/minified/attack_transformed.eval
    save_path: outputs/minified_base/attack_monitor_results.eval
    monitors:
      - untrusted_collusion_monitor
      - trusted_backdoor_monitor
      - untrusted_backdoor_monitor

  honest:
    eval_path: transforms/minified/honest_transformed.eval
    save_path: outputs/minified_base/honest_monitor_results.eval
    monitors:
      - untrusted_collusion_monitor
      - trusted_backdoor_monitor
      - untrusted_backdoor_monitor

  honeypots:
    eval_path: transforms/minified/honeypots_transformed.eval
    save_path: outputs/minified_base/honeypots_monitor_results.eval
    monitors:
      - untrusted_collusion_monitor
      - trusted_backdoor_monitor
      - untrusted_backdoor_monitor
